language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
services:
  - postgresql

before_script:
  - psql -c 'create database shopping_list_testing;' -U postgres

script:
  - nosetests -v
  - nosetests --with-coverage --cover-inclusive
  - "coveralls"

after_sucess:
  - "coveralls"