"""empty message

Revision ID: 4515306b1f5f
Revises: 8ce7ced7988b
Create Date: 2017-10-04 06:09:48.636506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4515306b1f5f'
down_revision = '8ce7ced7988b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('shoppinglists', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglists', 'modified_on')
    op.drop_column('items', 'modified_on')
    # ### end Alembic commands ###
