"""empty message

Revision ID: 65dd4262bfa7
Revises: 
Create Date: 2017-10-06 16:04:18.644959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dd4262bfa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('shared', sa.BOOLEAN(), nullable=True))
    op.add_column('shoppinglists', sa.Column('shared_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglists', 'shared_by')
    op.drop_column('shoppinglists', 'shared')
    # ### end Alembic commands ###
